# Generated by Django 5.2.4 on 2025-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('capacidade', models.PositiveIntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
