# Generated by Django 5.2.4 on 2025-08-05 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
