# Generated by Django 5.2.4 on 2025-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
