# Generated by Django 5.2.4 on 2025-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='observacoes',
            new_name='assistencia_detalhes',
        ),
        migrations.AddField(
            model_name='evento',
            name='observacao_organizador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('MINICURSO', 'Minicurso'), ('NETWORK', 'Networking'), ('OUTRO', 'Outro')], default='PALESTRA', max_length=20),
        ),
        migrations.AddField(
            model_name='participante',
            name='assistencia',
            field=models.CharField(choices=[('NENHUMA', 'Não preciso de assistência'), ('LOCOMOCAO', 'Assistência de locomoção'), ('AUDIOVISUAL', 'Apoio audiovisual (ex.: legendas, intérprete)'), ('OUTRA', 'Outro (descrever)')], default='NENHUMA', max_length=20),
        ),
    ]
